#!/bin/bash
PATH=/usr/local/cuda-8.0/bin:/usr/lib/llvm-4.0/bin:/apollo/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin: \
AFL_CXX=/apollo/clang/bin/clang++ \
exec /apollo/AFL/afl-clang-fast++ "$@"

